// Loads the ID-stamped panel drawing inline and hands out typed references to
// the interactive parts. The asset is generated by tools/build-panel-svg.mjs
// (from TouchPlaited; it is the same Simple Touch panel).

import panelSvg from '../../assets/panel.svg?raw';
import { CONTROLS, PADS } from '../core/controls-meta';

export interface KnobRef {
  g: SVGGElement;
  cx: number;
  cy: number;
}

export interface FaderRef {
  rect: SVGRectElement;
  minY: number; // handle y at value 1 (top)
  maxY: number; // handle y at value 0 (bottom)
}

export class Panel {
  readonly svg: SVGSVGElement;
  readonly knobs = new Map<number, KnobRef>();   // control index 0..5 (S30..S35)
  readonly faders = new Map<number, FaderRef>(); // control index 6..7 (S36..S37)
  readonly pads: SVGGraphicsElement[] = [];      // P0..P11
  readonly sw1: SVGGElement;
  readonly sw2: SVGGElement;
  readonly ledUser: SVGRectElement;

  constructor(container: HTMLElement) {
    container.innerHTML = panelSvg;
    this.svg = container.querySelector('svg')!;

    for (let i = 0; i < CONTROLS.length; i++) {
      const el = this.svg.querySelector<SVGGraphicsElement>(`#${CONTROLS[i].svgId}`);
      if (!el) throw new Error(`panel.svg is missing #${CONTROLS[i].svgId}`);
      if (el instanceof SVGGElement) {
        this.knobs.set(i, { g: el, cx: parseFloat(el.dataset.cx!), cy: parseFloat(el.dataset.cy!) });
      } else {
        this.faders.set(i, {
          rect: el as SVGRectElement,
          minY: parseFloat((el as SVGRectElement).dataset.minY!),
          maxY: parseFloat((el as SVGRectElement).dataset.maxY!),
        });
      }
    }

    for (const pad of PADS) {
      const el = this.svg.querySelector<SVGGraphicsElement>(`#${pad.svgId}`);
      if (!el) throw new Error(`panel.svg is missing #${pad.svgId}`);
      this.pads.push(el);
    }

    this.sw1 = this.svg.querySelector<SVGGElement>('#sw1')!;
    this.sw2 = this.svg.querySelector<SVGGElement>('#sw2')!;
    this.ledUser = this.svg.querySelector<SVGRectElement>('#led-user rect')!;
  }

  elementFor(svgId: string): SVGGraphicsElement | null {
    return this.svg.querySelector<SVGGraphicsElement>(`#${svgId}`);
  }

  /** The drawing element for control i (knob group or fader handle). */
  controlEl(i: number): SVGGraphicsElement | null {
    return this.knobs.get(i)?.g ?? this.faders.get(i)?.rect ?? null;
  }
}
